CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email   VARCHAR(255)                            NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT CHK_EMAIL_FORMAT CHECK (email ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
);

CREATE TABLE IF NOT EXISTS requests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    create_date TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_id_requests PRIMARY KEY (id),
    CONSTRAINT fk_requests_user_id FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR                                 NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    request_id BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_item_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_item_request_id FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date     TIMESTAMP WITH TIME ZONE                NOT NULL,
    end_date       TIMESTAMP WITH TIME ZONE                NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    item_id        BIGINT                                  NOT NULL,
    booking_status VARCHAR,
    CONSTRAINT pk_booking_id PRIMARY KEY (booking_id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES items (item_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id BIGINT                                  NOT NULL,
    text    VARCHAR                                 NOT NULL,
    user_id BIGINT                                  NOT NULL,
    created TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_comment_id PRIMARY KEY (id),
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES items (item_id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);
